sudo: required
services:
  - docker
before_install:
  - docker build -t karthik540/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true karthik540/react-test npm test
after_success:
  - docker build -t karthik540/multi-client ./client
  - docker build -t karthik540/multi-nginx ./nginx
  - docker build -t karthik540/multi-server ./server
  - docker build -t karthik540/multi-worker ./worker

  # Login to Docker hub..
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Pushing the images...
  - docker push karthik540/multi-client
  - docker push karthik540/multi-nginx
  - docker push karthik540/multi-server
  - docker push karthik540/multi-worker
  